theme: minima
title: GeorgeH712 GitHub Blog
author: George
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Learning to code with George. My journey through a Computer Science MSc and self-taught programming.

# social links
twitter_username:  # DO NOT include the @ character, or else the build will fail!
github_username:  Georgeh712 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
